name: syhunt test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Syhunt
        run: |
          # Coloque aqui os comandos necessários para configurar o ambiente do Syhunt

      - name: Run CodeScan
        run: |
          Start-CodeScan

      - name: Syhunt Report
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: syhunt-report
          path: report.pdf
          if-no-files-found: error
